jobs/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

app_name = 'jobs'
urlpatterns = [
    url(r"^$", views.home, name="home"),
    url(r"^jobs/(?P<href>[\d]+)/$",views.content,name="content"),
    url(r"^company/(?P<href>[\d]+)/$",views.company,name="company"),
    url(r"internship$",views.internship,name="internship"),
    url(r"fulltime$",views.fulltime,name="fulltime"),
    url(r"^status$",views.status,name="status"),
    url(r"^post$", TemplateView.as_view(template_name="jobs/post.html"), name="post"),
    #url(r"^post$", views.postjob, name="postjob"),
    url(r"^postmeetings$", TemplateView.as_view(template_name="jobs/postmeeting.html"), name="postmeetings"),
    url(r"^postcontests$", TemplateView.as_view(template_name="jobs/postcontest.html"), name="postcontests"),
    url(r"^search$",views.search,name="search"),
    url(r"^meetings$",views.meetingShow,name="meetings"),
    url(r"^meetings/(?P<href>[\d]+)/$",views.meetingcontent,name="meetingcontent"),
    url(r"^meetingpoststatus$",views.meetingpoststatus,name="meetingpoststatus"),
    url(r"^contests$",views.contestShow,name="contests"),
    url(r"^contests/(?P<href>[\d]+)/$",views.contestcontent,name="contestcontent"),
    url(r"^contestpoststatus$",views.contestpoststatus,name="contestpoststatus"),
]

nkustat/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.static import serve
from django.views.generic.base import RedirectView
from . import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('jobs.urls')),
    #url(r'^favicon\.ico$', RedirectView.as_view(url='/static/images/favicon.ico', permanent=True)),
    #url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="51datajobs">
    <meta name="author" content="nku-stat">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block head %}{% endblock %}
  </head>

  <body>
    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">展开</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">数据工作站</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li id="index" class="active"><a href="{% url 'jobs:home' %}">主页</a></li>
            <li id="fulltime"><a href="{% url 'jobs:fulltime' %}">全职</a></li>
            <li id="internship"><a href="{% url 'jobs:internship' %}">实习</a></li>
            <li id="post"><a href="{% url 'jobs:post' %}">我要招聘</a></li>
            <li id="meetings"><a href="{% url 'jobs:meetings' %}">学术会议</a></li>
            <li id="contests"><a href="{% url 'jobs:contests' %}">竞赛信息</a></li>
          </ul>
          <form class="navbar-form navbar-right" action="{% url 'jobs:search' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="搜索" name="word" required="required">
                    </div>
                    <div class="btn-group">
                        <input type="submit" class="btn btn-default" value="站内搜索">
                    </div>
                    <span>&nbsp;&nbsp;&nbsp;&nbsp;</span>
                </form>

        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </nav><!-- /.navbar -->

    <div class="container">
        <div class="row row-offcanvas row-offcanvas-right">
            <div class="col-xs-12 col-sm-9">
            <p class="pull-right visible-xs">
            <button type="button" class="btn btn-default btn-sm" data-toggle="offcanvas">侧栏</button>
            </p>
            {% block body %}{% endblock %}
            </div><!--/.col-xs-12.col-sm-9-->
            {% include 'jobs/sidebar.html' %}
        </div><!--row--> 
        {% include 'jobs/footer.html' %}
    </div><!--/.container-->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery.min.js'%}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap.min.js'%}" type="text/javascript"></script>
    <script src="{% static 'js/style.js'%}" type="text/javascript"></script>
    <!-- <script>window.jQuery || document.write('<script src="/static/js/jquery.min.js"><\/script>')</script> -->
    <script type="text/javascript">
        window.onload = function (){
            var path = document.location.pathname;
            var mainPath = path.split('/')[1];
            if (mainPath === ""){
                mainPath = "index";
            }
            var list = ["index","fulltime","internship","post","meetings","contests"];
            if (list.indexOf(mainPath) !== -1){
                var li = document.getElementById(mainPath);
                li.className = "active";
            }
       }
    </script>

    {% block script %}{% endblock %}
  </body>
</html>