jobs/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

app_name = 'jobs'
urlpatterns = [
    url(r"^$", views.home, name="home"),
    url(r"^jobs/(?P<href>[\d]+)/$",views.content,name="content"),
    url(r"^company/(?P<href>[\d]+)/$",views.company,name="company"),
    url(r"internship$",views.internship,name="internship"),
    url(r"fulltime$",views.fulltime,name="fulltime"),
    url(r"^status$",views.status,name="status"),
    url(r"^post$", TemplateView.as_view(template_name="jobs/post.html"), name="post"),
    #url(r"^post$", views.postjob, name="postjob"),
    url(r"^postmeetings$", TemplateView.as_view(template_name="jobs/postmeeting.html"), name="postmeetings"),
    url(r"^postcontests$", TemplateView.as_view(template_name="jobs/postcontest.html"), name="postcontests"),
    url(r"^search$",views.search,name="search"),
    url(r"^meetings$",views.meetingShow,name="meetings"),
    url(r"^meetings/(?P<href>[\d]+)/$",views.meetingcontent,name="meetingcontent"),
    url(r"^meetingpoststatus$",views.meetingpoststatus,name="meetingpoststatus"),
    url(r"^contests$",views.contestShow,name="contests"),
    url(r"^contests/(?P<href>[\d]+)/$",views.contestcontent,name="contestcontent"),
    url(r"^contestpoststatus$",views.contestpoststatus,name="contestpoststatus"),
]

nkustat/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.static import serve
from django.views.generic.base import RedirectView
from . import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('jobs.urls')),
    #url(r'^favicon\.ico$', RedirectView.as_view(url='/static/images/favicon.ico', permanent=True)),
    #url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

jobs/models.py
from django.db import models

# Create your models here.
from django.db import models

class Job(models.Model):
    companyName = models.CharField(max_length=50,verbose_name="公司名称")
    jobName = models.CharField(max_length=50,verbose_name="职位名称")
    jobInfo = models.TextField(max_length=4000,verbose_name="职位介绍")
    jobNeed = models.TextField(max_length=4000,verbose_name="职位要求")
    pubTime = models.DateTimeField(auto_now=True,verbose_name="发布日期")
    deadline = models.DateField(verbose_name="截止日期")
    isFullTime = models.BooleanField(default=False,verbose_name="全职")
    isPractice = models.BooleanField(default=False,verbose_name="兼职")
    website = models.CharField(max_length=200,blank=True,null=True,verbose_name="网址")
    contactEmail = models.CharField(max_length=30,verbose_name="联系人邮箱")
    publisherEmail = models.CharField(max_length=30,verbose_name="发布人邮箱")
    isPublish = models.BooleanField(default=False,verbose_name="发布")

    def __str__(self):
        return self.companyName


class Meeting(models.Model):
    meetingName = models.CharField(max_length=50,verbose_name="会议名称")
    pubTime = models.DateTimeField(auto_now=True,verbose_name="发布日期")
    startTime = models.DateField(verbose_name="会议开始日期")
    endTime = models.DateField(verbose_name="会议结束日期")
    place = models.CharField(max_length=200,verbose_name="会议地点")
    meetingInfo = models.TextField(max_length=4000,verbose_name="会议信息")
    website = models.CharField(max_length=200,blank=True,null=True,verbose_name="会议网址")
    isPublish = models.BooleanField(default=False,verbose_name="发布")

    def __str__(self):
        return self.meetingName

class Contest(models.Model):
    contestName = models.CharField(max_length=50,verbose_name="竞赛名称")
    contestInfo = models.TextField(max_length=4000,verbose_name="竞赛简介")
    pubTime = models.DateTimeField(auto_now=True,verbose_name="发布日期")
    website = models.CharField(max_length=200,blank=True,null=True,verbose_name="网址")
    isPublish = models.BooleanField(default=False,verbose_name="发布")

    def __str__(self):
        return self.contestName

class Link(models.Model):
    linkName = models.CharField(max_length=20,verbose_name="链接标题")
    website = models.CharField(max_length=200,verbose_name="网址")
    orderID = models.IntegerField(verbose_name="顺序ID")
    isPublish = models.BooleanField(default=False,verbose_name="发布")

    def __str__(self):
        return self.linkName

class Announcement(models.Model):
    annTitle = models.CharField(max_length=20,verbose_name="公告标题")
    annInfo = models.TextField(max_length=1000,verbose_name="公告内容")
    annLink = models.CharField(blank=True,max_length=200,verbose_name="详情链接(若无请不填)")
    orderID = models.IntegerField(verbose_name="顺序ID")
    isPublish = models.BooleanField(default=False,verbose_name="发布")

    def __str__(self):
        return self.annTitle

jobs/views.py
from django.shortcuts import render
from .models import *
import datetime
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.views.decorators.cache import cache_page

# Create your views here.

def paginate(request,jobs):
    paginator = Paginator(jobs,5)
    page = request.GET.get('page')
    if page is None:
        page = '1'
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        contacts = paginator.page(1)
        page = '1'
    except EmptyPage:
        contacts = paginator.page(paginator.num_pages)
        page = str(paginator.num_pages)
    pageNums = [str(i) for i in range(1,paginator.num_pages+1)]
    return contacts,page,pageNums

links = Link.objects.filter(isPublish=True).order_by('orderID')
announce = Announcement.objects.filter(isPublish=True).order_by('orderID')

@cache_page(60*15)
def home(request):
    jobs = Job.objects.filter(isPublish=True).order_by('pubTime').reverse()
    contacts,page,pageNums = paginate(request,jobs)
    return render(request, 'jobs/home.html', {"jobs":contacts,"page":page,"pageNums":pageNums,"pageNum":len(pageNums),'head':'数据工作站',"friendLinks":links,"Announce":announce,})

@cache_page(60*15)
def company(request,href):
    jobCompanyName = Job.objects.filter(isPublish=True,id=int(href))[0].companyName
    jobs = Job.objects.filter(isPublish=True,companyName=jobCompanyName).order_by('pubTime').reverse()
    contacts,page,pageNums = paginate(request,jobs)
    return render(request, 'jobs/home.html', {"jobs":contacts,"page":page,"pageNums":pageNums,"pageNum":len(pageNums),"head":jobCompanyName,"friendLinks":links,"Announce":announce,})

@cache_page(60*15)
def internship(request):
    jobs = Job.objects.filter(isPublish=True,isPractice=True).order_by('pubTime').reverse()
    contacts,page,pageNums = paginate(request,jobs)
    return render(request, 'jobs/home.html', {"jobs":contacts,"page":page,"pageNums":pageNums,"pageNum":len(pageNums),"head":"实习","friendLinks":links,"Announce":announce,})

@cache_page(60*15)
def fulltime(request):
    jobs = Job.objects.filter(isPublish=True,isFullTime=True).order_by('pubTime').reverse()
    contacts,page,pageNums = paginate(request,jobs)
    return render(request, 'jobs/home.html', {"jobs":contacts,"page":page,"pageNums":pageNums,"pageNum":len(pageNums),"head":"全职","friendLinks":links,"Announce":announce,})

@cache_page(60*15)
def search(request):
    try:
        word = request.POST['word']
    except:
        word = request.GET.get('word')
    title = "搜索--" + word
    jobs = []
    jobs += list(Job.objects.filter(isPublish=True,companyName__contains=word))
    jobs += list(Job.objects.filter(isPublish=True,jobName__contains=word))
    jobs += list(Job.objects.filter(isPublish=True,jobInfo__contains=word))
    jobs += list(Job.objects.filter(isPublish=True,jobNeed__contains=word))
    jobs = list(set(jobs))
    jobs.sort(key=lambda x:x.pubTime,reverse=True)
    contacts,page,pageNums = paginate(request,jobs)
    return render(request, 'jobs/search.html', {"word":word,"jobs":contacts,"page":page,"pageNums":pageNums,"pageNum":len(pageNums),"head":title,"friendLinks":links,"Announce":announce,})

@cache_page(60*15)
def content(request,href):
    job = Job.objects.filter(isPublish=True,id=int(href))[0]
    jobNeeds = job.jobNeed
    jobNeedList = jobNeeds.split(';')
    return render(request, 'jobs/content.html', {"job":job,"jobNeedList":jobNeedList,"friendLinks":links,"Announce":announce,})

@cache_page(60*15)
def status(request):
    companyName = request.POST['companyName']
    jobName = request.POST['jobName']
    jobInfo = request.POST['jobInfo']
    jobNeed = request.POST['jobNeed']
    deadline = request.POST['deadline']
    date = deadline.split('-')
    deadline = datetime.date(int(date[0]),int(date[1]),int(date[2]))
    website = request.POST['website']
    contactEmail = request.POST['contactEmail']
    publisherEmail = request.POST['publisherEmail']
    try:
        isFullTime = request.POST['isFullTime']
        isFullTime = True
    except:
        isFullTime = False
    try:
        isPractice = request.POST['isPractice']
        isPractice = True
    except:
        isPractice = False
    Job.objects.create(companyName=companyName,jobName=jobName,jobInfo=jobInfo,jobNeed=jobNeed,deadline=deadline,website=website,contactEmail=contactEmail,publisherEmail=publisherEmail,isFullTime=isFullTime,isPractice=isPractice)
    return render(request, 'jobs/status.html', {"head":"提交招聘信息","status":"提交成功!请耐心等待审核!","friendLinks":links,"Announce":announce,})
    
@cache_page(60*15)
def meetingpoststatus(request):
    meetingName = request.POST['meetingName']
    startTime = request.POST['startTime']
    date =startTime.split('-')
    startTime = datetime.date(int(date[0]),int(date[1]),int(date[2]))
    endTime = request.POST['endTime']
    date = endTime.split('-')
    endTime = datetime.date(int(date[0]),int(date[1]),int(date[2]))
    place = request.POST['place']
    meetingInfo = request.POST['meetingInfo']
    website = request.POST['website']
    Meeting.objects.create(meetingName=meetingName,startTime=startTime,endTime=endTime,place=place,meetingInfo=meetingInfo,website=website)
    return render(request, 'jobs/status.html', {"head":"提交会议信息","status":"提交成功!请耐心等待审核!","friendLinks":links,"Announce":announce,})

@cache_page(60*15)
def meetingShow(request):
    meetings = Meeting.objects.filter(isPublish=True).order_by('startTime').reverse()
    contacts,page,pageNums = paginate(request,meetings)
    return render(request, 'jobs/meetings.html', {"jobs":contacts,"page":page,"pageNums":pageNums,"pageNum":len(pageNums),"friendLinks":links,"Announce":announce,})

@cache_page(60*15)
def meetingcontent(request,href):
    meeting = Meeting.objects.filter(isPublish=True,id=int(href))[0]
    return render(request, 'jobs/meetingcontent.html', {"meeting":meeting,"friendLinks":links,"Announce":announce,})

@cache_page(60*15)
def contestpoststatus(request):
    contestName = request.POST['contestName']
    contestInfo = request.POST['contestInfo']
    website = request.POST['website']
    Contest.objects.create(contestName=contestName,contestInfo=contestInfo,website=website)
    return render(request, 'jobs/status.html', {"head":"提交竞赛信息","status":"提交成功!请耐心等待审核!","friendLinks":links,"Announce":announce,})

@cache_page(60*15)
def contestShow(request):
    contests = Contest.objects.filter(isPublish=True).order_by('pubTime').reverse()
    contacts,page,pageNums = paginate(request,contests)
    return render(request, 'jobs/contests.html', {"jobs":contacts,"page":page,"pageNums":pageNums,"pageNum":len(pageNums),"friendLinks":links,"Announce":announce,})

@cache_page(60*15)
def contestcontent(request,href):
    contest = Contest.objects.filter(isPublish=True,id=int(href))[0]
    return render(request, 'jobs/contestcontent.html', {"contest":contest,"friendLinks":links,"Announce":announce,})

templates/jobs/contests.html
{% extends "base.html" %}
{% block title %}
竞赛信息
{% endblock %}
{% block body %}
          <div class="page-header">
              <h1>竞赛信息</h1>
          </div>
          
          <div class="row">
              <div class="col-md-6 col-md-offset-10">
              <a class="btn btn-primary btn-sm" href="{% url 'jobs:postcontests' %}" role="button">发布新竞赛 &raquo;</a>
              </div>
              <br>
              <br>
              {% for foo in jobs %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-md-12">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                    &nbsp;竞赛名称:&nbsp;&nbsp;<a href="{% url 'jobs:contestcontent' foo.id %}">{{ foo.contestName }}</a>
                </div>
                
            </div>
        </div>
    <div class="panel-body">
        <p class="paragraph">{{ foo.contestInfo | slice:"300" }}…</p>
        <p class="paragraph"><a class="btn btn-default btn-sm" href={% url 'jobs:contestcontent' foo.id %} role="button">查看详情 &raquo;</a></p>
    </div>
    <div class="panel-footer">
        <div class="row">
            <div class="col-md-12">
                <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                &nbsp;发布时间:&nbsp;&nbsp;&nbsp;{{ foo.pubTime }}
            </div>
        </div>
    </div>
    </div>
    {% endfor %}

          </div><!--/row-->
          {% include './nav.html' %}
{% endblock %}

templates/jobs/home.html
{% extends "base.html" %}
{% block title %}
{{ head }}
{% endblock %}
{% block body %}
    <div class="page-header">
        <h1>{{ head }}</h1>
    </div>
    <div class="row">
        <div class="col-md-6 col-md-offset-10">
        <a class="btn btn-primary btn-sm" href="{% url 'jobs:post' %}" role="button">发布新招聘 &raquo;</a>
        </div>
        <br><br>
        {% for foo in jobs %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-md-8">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                    &nbsp;职位名称:&nbsp;&nbsp;<a href="{% url 'jobs:content' foo.id %}">{{ foo.jobName }}</a>
                </div>
                <div class="col-md-4">
                    {% ifequal foo.isFullTime True %}
                    &nbsp;&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-tag" aria-hidden="true"></span>&nbsp;类别:&nbsp;&nbsp;<a href="{% url 'jobs:fulltime' %}">全职</a>
                    {% endifequal %}
                    {% ifequal foo.isPractice True %}
                    &nbsp;&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-tag" aria-hidden="true"></span>&nbsp;类别:&nbsp;&nbsp;<a href="{% url 'jobs:internship' %}">实习</a>
                    {% endifequal %}
                </div>
            </div>
        </div>
    <div class="panel-body">
        <p class="paragraph">{{ foo.jobInfo | slice:"300" }}…</p>
        <p class="paragraph"><a class="btn btn-default btn-sm" href={% url 'jobs:content' foo.id %} role="button">查看详情 &raquo;</a></p>
    </div>
    <div class="panel-footer">
        <div class="row">
            <div class="col-md-8">
                <span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>
                &nbsp;公司名称:&nbsp;&nbsp;<a href="{% url 'jobs:company' foo.id %}">{{ foo.companyName }}</a>
            </div>
            <div class="col-md-4">
                <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                &nbsp;发布时间:&nbsp;&nbsp;&nbsp;{{ foo.pubTime }}
            </div>
        </div>
    </div>
    </div>
    {% endfor %}
      </div><!--/row-->
    {% include './nav.html' %}
{% endblock %}

templates/jobs/meetings.html
{% extends "base.html" %}
{% block title %}
学术会议
{% endblock %}
{% block body %}
          <div class="page-header">
              <h1>学术会议</h1>
          </div>
          
          <div class="row">
              <div class="col-md-10">
                  <p style="color:red;font-size:12px;">*以下会议按举办日期排序</p>
              </div>
              <div class="col-md-2">
              <a class="btn btn-primary btn-sm" href="{% url 'jobs:postmeetings' %}" role="button">发布新会议 &raquo;</a>
              </div>
              <br>
              <br>
              {% for foo in jobs %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-md-12">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                    &nbsp;会议名称:&nbsp;&nbsp;<a href="{% url 'jobs:meetingcontent' foo.id %}">{{ foo.meetingName }}</a>
                </div>
            </div>
        </div>
    <div class="panel-body">
        <p class="paragraph">{{ foo.meetingInfo | slice:"300" }}…</p>
        <p class="paragraph"><a class="btn btn-default btn-sm" href={% url 'jobs:meetingcontent' foo.id %} role="button">查看详情 &raquo;</a></p>
    </div>
    <div class="panel-footer">
        <div class="row">
            <div class="col-md-8">
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                &nbsp;会议地点:&nbsp;&nbsp;{{ foo.place }}
            </div>
            <div class="col-md-4">
                <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                &nbsp;会议日期:&nbsp;&nbsp;{{ foo.startTime }}
            </div>
            <div class="col-md-6">
            </div>
        </div>
    </div>
    </div>
    {% endfor %}

          </div><!--/row-->
          {% include './nav.html' %}
{% endblock %}

templates/jobs/post.html
{% extends "base.html" %}
{% block title %}
提交招聘信息
{% endblock %}
{% block body %}
    <div class="page-header">
        <h1>提交招聘信息</h1>
    </div>
    <div class="row">
    <p>请将您的招聘信息填写在下面的表单中，并点击提交按钮，通过审核后将会显示在主页。如有问题请联系<a href="mailto:nk_datajobs@163.com">nk_datajobs@163.com</a>。<p>
    <form action="{% url 'jobs:status' %}" method="post">
{% csrf_token %}
    <div class="input-group">
        <span class="input-group-addon">公司名称*</span>
        <input type="text" class="form-control" name="companyName" placeholder="公司名称" required="required">
    </div>
    <br/>
    <div class="input-group">
        <span class="input-group-addon">职位名称*</span>
        <input type="text" class="form-control" name="jobName" placeholder="职位名称" required="required">
    </div>
    <br/>
    <div class="input-group">
        <span class="input-group-addon">职位介绍*</span>
        <textarea rows="6" class="form-control" name="jobInfo" placeholder="职位介绍(限2000字以内)" required="required"></textarea>
    </div>
    <br/>
    <div class="input-group">
        <span class="input-group-addon">职位要求*</span>
        <textarea rows="6" class="form-control" name="jobNeed" placeholder="职位要求(限2000字以内),多条可用英文分号隔开" required="required"></textarea>
    </div>
    <br/>
    <div class="input-group">
        <span class="input-group-addon">截止日期*</span>
        <input type="date" class="form-control" name="deadline" required="required">
    </div>
    <br/>
    <div class="input-group">
        <span class="input-group-addon">网址</span>
        <input type="url" class="form-control" name="website" placeholder="http://example.com">
    </div>
    <br/>
    <div class="input-group">
        <span class="input-group-addon">联系人邮箱*</span>
        <input type="email" class="form-control" name="contactEmail" placeholder="someone@example.com" required="required">
    </div>
    <br/>
    <div class="input-group">
        <span class="input-group-addon">发布人邮箱*</span>
        <input type="email" class="form-control" name="publisherEmail" placeholder="someone@example.com" required="required">
    </div>
    <br/>
    <div class="row">
        <div class="col-xs-3 col-xs-offset-1">
        <label class="checkbox-inline">
            <input type="checkbox" name="isFullTime">全职
        </label>
        </div>
        <div class="col-xs-3">
        <label class="checkbox-inline">
            <input type="checkbox" name="isPractice">实习
        </label>
        </div>
        <div class="col-xs-2 col-xs-offset-1">
        <input type="submit" class="btn btn-default" value="提交">
        </div>
    </div>
    </form>
    </div><!--/row-->
{% endblock %}

templates/jobs/postcontest.html
{% extends "base.html" %}
{% block title %}
提交竞赛信息
{% endblock %}
{% block body %}
    <div class="page-header">
        <h1>提交竞赛信息</h1>
    </div>
    <div class="row">
        <p>请将竞赛信息填写在下面的表单中，并点击提交按钮，通过审核后将会显示在主页。如有问题请联系<a href="mailto:nk_datajobs@163.com">nk_datajobs@163.com</a>。<p>
        <form action="{% url 'jobs:contestpoststatus' %}" method="post">
{% csrf_token %}
    <div class="input-group">
        <span class="input-group-addon">竞赛名称*</span>
        <input type="text" class="form-control" name="contestName" placeholder="竞赛名称" required="required">
    </div>
    <br/>
    <div class="input-group">
        <span class="input-group-addon">竞赛简介*</span>
        <textarea rows="6" class="form-control" name="contestInfo" placeholder="竞赛简介(限2000字以内)" required="required"></textarea>
    </div>
    <br/>
    <div class="input-group">
        <span class="input-group-addon">竞赛网址</span>
        <input type="url" class="form-control" name="website" placeholder="http://example.com">
    </div>
    <br/>
    <div class="row">
        <div class="col-xs-3 col-xs-offset-5">
        <input type="submit" class="btn btn-default" value="提交">
        </div>
    </div>
</form>

    </div><!--/row-->
{% endblock %}

templates/jobs/postmeeting.html
{% extends "base.html" %}
{% block title %}
提交会议信息
{% endblock %}
{% block body %}
    <div class="page-header">
        <h1>提交会议信息</h1>
    </div>
    <div class="row">
        <p>请将会议信息填写在下面的表单中，并点击提交按钮，通过审核后将会显示在主页。如有问题请联系<a href="mailto:nk_datajobs@163.com">nk_datajobs@163.com</a>。<p>
        <form action="{% url 'jobs:meetingpoststatus' %}" method="post">
{% csrf_token %}
    <div class="input-group">
        <span class="input-group-addon">会议名称*</span>
        <input type="text" class="form-control" name="meetingName" placeholder="会议名称" required="required">
    </div>
    <br/>
    <div class="input-group">
        <span class="input-group-addon">会议开始日期*</span>
        <input type="date" class="form-control" name="startTime" required="required">
    </div>
    <br/>
    <div class="input-group">
        <span class="input-group-addon">会议结束日期*</span>
        <input type="date" class="form-control" name="endTime" required="required">
    </div>
    <br/>
    <div class="input-group">
        <span class="input-group-addon">会议地点*</span>
        <input type="text" class="form-control" name="place" placeholder="会议地点" required="required">
    </div>
    <br/>
    <div class="input-group">
        <span class="input-group-addon">会议信息*</span>
        <textarea rows="6" class="form-control" name="meetingInfo" placeholder="会议信息(限2000字以内)" required="required"></textarea>
    </div>
    <br/>
    <div class="input-group">
        <span class="input-group-addon">会议网址</span>
        <input type="url" class="form-control" name="website" placeholder="http://example.com">
    </div>
    <br/>
    <div class="row">
        <div class="col-xs-3 col-xs-offset-5">
        <input type="submit" class="btn btn-default" value="提交">
        </div>
    </div>
</form>

    </div><!--/row-->
{% endblock %}

templates/jobs/search.html
{% extends "base.html" %}
{% block title %}
{{ head }}
{% endblock %}
{% block body %}
    <div class="page-header">
        <h1>{{ head }}</h1>
    </div>
    <div class="row">
        {% for foo in jobs %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-md-6">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                    &nbsp;职位名称:&nbsp;&nbsp;<a href="{% url 'jobs:content' foo.id %}">{{ foo.jobName }}</a>
                </div>
                <div class="col-md-6">
                    {% ifequal foo.isFullTime True %}
                    &nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'jobs:fulltime' %}">全职</a>&nbsp;&nbsp;
                    {% endifequal %}
                    {% ifequal foo.isPractice True %}
                    &nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'jobs:internship' %}">实习</a>&nbsp;&nbsp;
                    {% endifequal %}
                </div>
            </div>
        </div>
    <div class="panel-body">
        <p class="paragraph">{{ foo.jobInfo | slice:"300" }}…</p>
        <p class="paragraph"><a href={% url 'jobs:content' foo.id %}>查看更多</a></p>
    </div>
    <div class="panel-footer">
        <div class="row">
            <div class="col-md-6">
                <span class="glyphicon glyphicon-phone-alt" aria-hidden="true"></span>
                &nbsp;公司名称:&nbsp;&nbsp;<a href="{% url 'jobs:company' foo.id %}">{{ foo.companyName }}</a>
            </div>
            <div class="col-md-6">
                <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                &nbsp;发布时间:&nbsp;&nbsp;&nbsp;{{ foo.pubTime }}
            </div>
        </div>
    </div>
    </div>
    {% endfor %}

          </div><!--/row-->
{% ifnotequal pageNum 1 %}
<div class="container">
    <nav style="text-align: center">
        <ul class="pagination">
            {% if jobs.has_previous %}
                <li>
                    <a href="?page={{ jobs.previous_page_number }}&word={{ word }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% else %}
                <li class="disabled">
                    <a>
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}
        
            {% for foo in pageNums%}
                {% ifequal foo page %}
                    <li class="active"><a href="?page={{ foo }}&word={{ word }}">{{ foo }}</a></li>
                {% else %}
                    <li><a href="?page={{ foo }}&word={{ word }}">{{ foo }}</a></li>
                {% endifequal %}
            {% endfor %}

            {% if jobs.has_next %}
                <li>
                    <a href="?page={{ jobs.next_page_number }}&word={{ word }}" aria-label="Previous">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% else %}
                <li class="disabled">
                    <a>
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endifnotequal %}
{% endblock %}